packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: false
  msgpackr-extract: false

auditConfig:
  ignoreDependencies:
    - '@benjavicente/*'
  ignoreGhsas:
    - GHSA-4hxc-9384-m385
    - GHSA-q5pr-72pq-83v3
    - GHSA-2j6q-whv2-gh6w

minimumReleaseAgeExclude:
  - '@benjavicente/*'
