/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as shopCheckoutRouteImport } from './routes/(shop)/checkout'
import { Route as shopCartRouteImport } from './routes/(shop)/cart'
import { Route as legalUnauthorizedRouteImport } from './routes/(legal)/unauthorized'
import { Route as legalTermsAndConditionsRouteImport } from './routes/(legal)/terms-and-conditions'
import { Route as accountProfileRouteImport } from './routes/(account)/profile'
import { Route as shopCheckoutIndexRouteImport } from './routes/(shop)/checkout.index'
import { Route as pizzeriasPizzeriasIndexRouteImport } from './routes/(pizzerias)/pizzerias.index'
import { Route as ordersOrdersIndexRouteImport } from './routes/(orders)/orders.index'
import { Route as shopCheckoutScheduleRouteImport } from './routes/(shop)/checkout.schedule'
import { Route as shopCheckoutReviewRouteImport } from './routes/(shop)/checkout.review'
import { Route as shopCheckoutDeliveryRouteImport } from './routes/(shop)/checkout.delivery'
import { Route as pizzeriasPizzeriasAdminRouteImport } from './routes/(pizzerias)/pizzerias.admin'
import { Route as pizzeriasPizzeriasIdRouteImport } from './routes/(pizzerias)/pizzerias.$id'
import { Route as ordersOrdersAdminRouteImport } from './routes/(orders)/orders.admin'
import { Route as ordersOrdersIdRouteImport } from './routes/(orders)/orders.$id'
import { Route as authAuthRegisterPizzeriaRouteImport } from './routes/(auth)/auth.register-pizzeria'
import { Route as authAuthRegisterRouteImport } from './routes/(auth)/auth.register'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth.login'
import { Route as pizzeriasPizzeriasAdminIndexRouteImport } from './routes/(pizzerias)/pizzerias.admin.index'
import { Route as pizzeriasPizzeriasAdminPizzasRouteImport } from './routes/(pizzerias)/pizzerias.admin.pizzas'
import { Route as pizzeriasPizzeriasAdminNewRouteImport } from './routes/(pizzerias)/pizzerias.admin.new'
import { Route as pizzeriasPizzeriasAdminConfigurationRouteImport } from './routes/(pizzerias)/pizzerias.admin.configuration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCheckoutRoute = shopCheckoutRouteImport.update({
  id: '/(shop)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCartRoute = shopCartRouteImport.update({
  id: '/(shop)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const legalUnauthorizedRoute = legalUnauthorizedRouteImport.update({
  id: '/(legal)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const legalTermsAndConditionsRoute = legalTermsAndConditionsRouteImport.update({
  id: '/(legal)/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const accountProfileRoute = accountProfileRouteImport.update({
  id: '/(account)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCheckoutIndexRoute = shopCheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => shopCheckoutRoute,
} as any)
const pizzeriasPizzeriasIndexRoute = pizzeriasPizzeriasIndexRouteImport.update({
  id: '/(pizzerias)/pizzerias/',
  path: '/pizzerias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ordersOrdersIndexRoute = ordersOrdersIndexRouteImport.update({
  id: '/(orders)/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCheckoutScheduleRoute = shopCheckoutScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => shopCheckoutRoute,
} as any)
const shopCheckoutReviewRoute = shopCheckoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => shopCheckoutRoute,
} as any)
const shopCheckoutDeliveryRoute = shopCheckoutDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => shopCheckoutRoute,
} as any)
const pizzeriasPizzeriasAdminRoute = pizzeriasPizzeriasAdminRouteImport.update({
  id: '/(pizzerias)/pizzerias/admin',
  path: '/pizzerias/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const pizzeriasPizzeriasIdRoute = pizzeriasPizzeriasIdRouteImport.update({
  id: '/(pizzerias)/pizzerias/$id',
  path: '/pizzerias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ordersOrdersAdminRoute = ordersOrdersAdminRouteImport.update({
  id: '/(orders)/orders/admin',
  path: '/orders/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ordersOrdersIdRoute = ordersOrdersIdRouteImport.update({
  id: '/(orders)/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRegisterPizzeriaRoute =
  authAuthRegisterPizzeriaRouteImport.update({
    id: '/(auth)/auth/register-pizzeria',
    path: '/auth/register-pizzeria',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: '/(auth)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/(auth)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const pizzeriasPizzeriasAdminIndexRoute =
  pizzeriasPizzeriasAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => pizzeriasPizzeriasAdminRoute,
  } as any)
const pizzeriasPizzeriasAdminPizzasRoute =
  pizzeriasPizzeriasAdminPizzasRouteImport.update({
    id: '/pizzas',
    path: '/pizzas',
    getParentRoute: () => pizzeriasPizzeriasAdminRoute,
  } as any)
const pizzeriasPizzeriasAdminNewRoute =
  pizzeriasPizzeriasAdminNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => pizzeriasPizzeriasAdminRoute,
  } as any)
const pizzeriasPizzeriasAdminConfigurationRoute =
  pizzeriasPizzeriasAdminConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => pizzeriasPizzeriasAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof accountProfileRoute
  '/terms-and-conditions': typeof legalTermsAndConditionsRoute
  '/unauthorized': typeof legalUnauthorizedRoute
  '/cart': typeof shopCartRoute
  '/checkout': typeof shopCheckoutRouteWithChildren
  '/auth/login': typeof authAuthLoginRoute
  '/auth/register': typeof authAuthRegisterRoute
  '/auth/register-pizzeria': typeof authAuthRegisterPizzeriaRoute
  '/orders/$id': typeof ordersOrdersIdRoute
  '/orders/admin': typeof ordersOrdersAdminRoute
  '/pizzerias/$id': typeof pizzeriasPizzeriasIdRoute
  '/pizzerias/admin': typeof pizzeriasPizzeriasAdminRouteWithChildren
  '/checkout/delivery': typeof shopCheckoutDeliveryRoute
  '/checkout/review': typeof shopCheckoutReviewRoute
  '/checkout/schedule': typeof shopCheckoutScheduleRoute
  '/orders/': typeof ordersOrdersIndexRoute
  '/pizzerias/': typeof pizzeriasPizzeriasIndexRoute
  '/checkout/': typeof shopCheckoutIndexRoute
  '/pizzerias/admin/configuration': typeof pizzeriasPizzeriasAdminConfigurationRoute
  '/pizzerias/admin/new': typeof pizzeriasPizzeriasAdminNewRoute
  '/pizzerias/admin/pizzas': typeof pizzeriasPizzeriasAdminPizzasRoute
  '/pizzerias/admin/': typeof pizzeriasPizzeriasAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof accountProfileRoute
  '/terms-and-conditions': typeof legalTermsAndConditionsRoute
  '/unauthorized': typeof legalUnauthorizedRoute
  '/cart': typeof shopCartRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/register': typeof authAuthRegisterRoute
  '/auth/register-pizzeria': typeof authAuthRegisterPizzeriaRoute
  '/orders/$id': typeof ordersOrdersIdRoute
  '/orders/admin': typeof ordersOrdersAdminRoute
  '/pizzerias/$id': typeof pizzeriasPizzeriasIdRoute
  '/checkout/delivery': typeof shopCheckoutDeliveryRoute
  '/checkout/review': typeof shopCheckoutReviewRoute
  '/checkout/schedule': typeof shopCheckoutScheduleRoute
  '/orders': typeof ordersOrdersIndexRoute
  '/pizzerias': typeof pizzeriasPizzeriasIndexRoute
  '/checkout': typeof shopCheckoutIndexRoute
  '/pizzerias/admin/configuration': typeof pizzeriasPizzeriasAdminConfigurationRoute
  '/pizzerias/admin/new': typeof pizzeriasPizzeriasAdminNewRoute
  '/pizzerias/admin/pizzas': typeof pizzeriasPizzeriasAdminPizzasRoute
  '/pizzerias/admin': typeof pizzeriasPizzeriasAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(account)/profile': typeof accountProfileRoute
  '/(legal)/terms-and-conditions': typeof legalTermsAndConditionsRoute
  '/(legal)/unauthorized': typeof legalUnauthorizedRoute
  '/(shop)/cart': typeof shopCartRoute
  '/(shop)/checkout': typeof shopCheckoutRouteWithChildren
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/register': typeof authAuthRegisterRoute
  '/(auth)/auth/register-pizzeria': typeof authAuthRegisterPizzeriaRoute
  '/(orders)/orders/$id': typeof ordersOrdersIdRoute
  '/(orders)/orders/admin': typeof ordersOrdersAdminRoute
  '/(pizzerias)/pizzerias/$id': typeof pizzeriasPizzeriasIdRoute
  '/(pizzerias)/pizzerias/admin': typeof pizzeriasPizzeriasAdminRouteWithChildren
  '/(shop)/checkout/delivery': typeof shopCheckoutDeliveryRoute
  '/(shop)/checkout/review': typeof shopCheckoutReviewRoute
  '/(shop)/checkout/schedule': typeof shopCheckoutScheduleRoute
  '/(orders)/orders/': typeof ordersOrdersIndexRoute
  '/(pizzerias)/pizzerias/': typeof pizzeriasPizzeriasIndexRoute
  '/(shop)/checkout/': typeof shopCheckoutIndexRoute
  '/(pizzerias)/pizzerias/admin/configuration': typeof pizzeriasPizzeriasAdminConfigurationRoute
  '/(pizzerias)/pizzerias/admin/new': typeof pizzeriasPizzeriasAdminNewRoute
  '/(pizzerias)/pizzerias/admin/pizzas': typeof pizzeriasPizzeriasAdminPizzasRoute
  '/(pizzerias)/pizzerias/admin/': typeof pizzeriasPizzeriasAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/terms-and-conditions'
    | '/unauthorized'
    | '/cart'
    | '/checkout'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-pizzeria'
    | '/orders/$id'
    | '/orders/admin'
    | '/pizzerias/$id'
    | '/pizzerias/admin'
    | '/checkout/delivery'
    | '/checkout/review'
    | '/checkout/schedule'
    | '/orders/'
    | '/pizzerias/'
    | '/checkout/'
    | '/pizzerias/admin/configuration'
    | '/pizzerias/admin/new'
    | '/pizzerias/admin/pizzas'
    | '/pizzerias/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/terms-and-conditions'
    | '/unauthorized'
    | '/cart'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-pizzeria'
    | '/orders/$id'
    | '/orders/admin'
    | '/pizzerias/$id'
    | '/checkout/delivery'
    | '/checkout/review'
    | '/checkout/schedule'
    | '/orders'
    | '/pizzerias'
    | '/checkout'
    | '/pizzerias/admin/configuration'
    | '/pizzerias/admin/new'
    | '/pizzerias/admin/pizzas'
    | '/pizzerias/admin'
  id:
    | '__root__'
    | '/'
    | '/(account)/profile'
    | '/(legal)/terms-and-conditions'
    | '/(legal)/unauthorized'
    | '/(shop)/cart'
    | '/(shop)/checkout'
    | '/(auth)/auth/login'
    | '/(auth)/auth/register'
    | '/(auth)/auth/register-pizzeria'
    | '/(orders)/orders/$id'
    | '/(orders)/orders/admin'
    | '/(pizzerias)/pizzerias/$id'
    | '/(pizzerias)/pizzerias/admin'
    | '/(shop)/checkout/delivery'
    | '/(shop)/checkout/review'
    | '/(shop)/checkout/schedule'
    | '/(orders)/orders/'
    | '/(pizzerias)/pizzerias/'
    | '/(shop)/checkout/'
    | '/(pizzerias)/pizzerias/admin/configuration'
    | '/(pizzerias)/pizzerias/admin/new'
    | '/(pizzerias)/pizzerias/admin/pizzas'
    | '/(pizzerias)/pizzerias/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  accountProfileRoute: typeof accountProfileRoute
  legalTermsAndConditionsRoute: typeof legalTermsAndConditionsRoute
  legalUnauthorizedRoute: typeof legalUnauthorizedRoute
  shopCartRoute: typeof shopCartRoute
  shopCheckoutRoute: typeof shopCheckoutRouteWithChildren
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
  authAuthRegisterPizzeriaRoute: typeof authAuthRegisterPizzeriaRoute
  ordersOrdersIdRoute: typeof ordersOrdersIdRoute
  ordersOrdersAdminRoute: typeof ordersOrdersAdminRoute
  pizzeriasPizzeriasIdRoute: typeof pizzeriasPizzeriasIdRoute
  pizzeriasPizzeriasAdminRoute: typeof pizzeriasPizzeriasAdminRouteWithChildren
  ordersOrdersIndexRoute: typeof ordersOrdersIndexRoute
  pizzeriasPizzeriasIndexRoute: typeof pizzeriasPizzeriasIndexRoute
}

declare module '@benjavicente/angular-router-experimental' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/checkout': {
      id: '/(shop)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof shopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/cart': {
      id: '/(shop)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof shopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/unauthorized': {
      id: '/(legal)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof legalUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/terms-and-conditions': {
      id: '/(legal)/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof legalTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(account)/profile': {
      id: '/(account)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof accountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/checkout/': {
      id: '/(shop)/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof shopCheckoutIndexRouteImport
      parentRoute: typeof shopCheckoutRoute
    }
    '/(pizzerias)/pizzerias/': {
      id: '/(pizzerias)/pizzerias/'
      path: '/pizzerias'
      fullPath: '/pizzerias/'
      preLoaderRoute: typeof pizzeriasPizzeriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(orders)/orders/': {
      id: '/(orders)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ordersOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/checkout/schedule': {
      id: '/(shop)/checkout/schedule'
      path: '/schedule'
      fullPath: '/checkout/schedule'
      preLoaderRoute: typeof shopCheckoutScheduleRouteImport
      parentRoute: typeof shopCheckoutRoute
    }
    '/(shop)/checkout/review': {
      id: '/(shop)/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof shopCheckoutReviewRouteImport
      parentRoute: typeof shopCheckoutRoute
    }
    '/(shop)/checkout/delivery': {
      id: '/(shop)/checkout/delivery'
      path: '/delivery'
      fullPath: '/checkout/delivery'
      preLoaderRoute: typeof shopCheckoutDeliveryRouteImport
      parentRoute: typeof shopCheckoutRoute
    }
    '/(pizzerias)/pizzerias/admin': {
      id: '/(pizzerias)/pizzerias/admin'
      path: '/pizzerias/admin'
      fullPath: '/pizzerias/admin'
      preLoaderRoute: typeof pizzeriasPizzeriasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pizzerias)/pizzerias/$id': {
      id: '/(pizzerias)/pizzerias/$id'
      path: '/pizzerias/$id'
      fullPath: '/pizzerias/$id'
      preLoaderRoute: typeof pizzeriasPizzeriasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(orders)/orders/admin': {
      id: '/(orders)/orders/admin'
      path: '/orders/admin'
      fullPath: '/orders/admin'
      preLoaderRoute: typeof ordersOrdersAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(orders)/orders/$id': {
      id: '/(orders)/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof ordersOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/register-pizzeria': {
      id: '/(auth)/auth/register-pizzeria'
      path: '/auth/register-pizzeria'
      fullPath: '/auth/register-pizzeria'
      preLoaderRoute: typeof authAuthRegisterPizzeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/register': {
      id: '/(auth)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pizzerias)/pizzerias/admin/': {
      id: '/(pizzerias)/pizzerias/admin/'
      path: '/'
      fullPath: '/pizzerias/admin/'
      preLoaderRoute: typeof pizzeriasPizzeriasAdminIndexRouteImport
      parentRoute: typeof pizzeriasPizzeriasAdminRoute
    }
    '/(pizzerias)/pizzerias/admin/pizzas': {
      id: '/(pizzerias)/pizzerias/admin/pizzas'
      path: '/pizzas'
      fullPath: '/pizzerias/admin/pizzas'
      preLoaderRoute: typeof pizzeriasPizzeriasAdminPizzasRouteImport
      parentRoute: typeof pizzeriasPizzeriasAdminRoute
    }
    '/(pizzerias)/pizzerias/admin/new': {
      id: '/(pizzerias)/pizzerias/admin/new'
      path: '/new'
      fullPath: '/pizzerias/admin/new'
      preLoaderRoute: typeof pizzeriasPizzeriasAdminNewRouteImport
      parentRoute: typeof pizzeriasPizzeriasAdminRoute
    }
    '/(pizzerias)/pizzerias/admin/configuration': {
      id: '/(pizzerias)/pizzerias/admin/configuration'
      path: '/configuration'
      fullPath: '/pizzerias/admin/configuration'
      preLoaderRoute: typeof pizzeriasPizzeriasAdminConfigurationRouteImport
      parentRoute: typeof pizzeriasPizzeriasAdminRoute
    }
  }
}

interface shopCheckoutRouteChildren {
  shopCheckoutDeliveryRoute: typeof shopCheckoutDeliveryRoute
  shopCheckoutReviewRoute: typeof shopCheckoutReviewRoute
  shopCheckoutScheduleRoute: typeof shopCheckoutScheduleRoute
  shopCheckoutIndexRoute: typeof shopCheckoutIndexRoute
}

const shopCheckoutRouteChildren: shopCheckoutRouteChildren = {
  shopCheckoutDeliveryRoute: shopCheckoutDeliveryRoute,
  shopCheckoutReviewRoute: shopCheckoutReviewRoute,
  shopCheckoutScheduleRoute: shopCheckoutScheduleRoute,
  shopCheckoutIndexRoute: shopCheckoutIndexRoute,
}

const shopCheckoutRouteWithChildren = shopCheckoutRoute._addFileChildren(
  shopCheckoutRouteChildren,
)

interface pizzeriasPizzeriasAdminRouteChildren {
  pizzeriasPizzeriasAdminConfigurationRoute: typeof pizzeriasPizzeriasAdminConfigurationRoute
  pizzeriasPizzeriasAdminNewRoute: typeof pizzeriasPizzeriasAdminNewRoute
  pizzeriasPizzeriasAdminPizzasRoute: typeof pizzeriasPizzeriasAdminPizzasRoute
  pizzeriasPizzeriasAdminIndexRoute: typeof pizzeriasPizzeriasAdminIndexRoute
}

const pizzeriasPizzeriasAdminRouteChildren: pizzeriasPizzeriasAdminRouteChildren =
  {
    pizzeriasPizzeriasAdminConfigurationRoute:
      pizzeriasPizzeriasAdminConfigurationRoute,
    pizzeriasPizzeriasAdminNewRoute: pizzeriasPizzeriasAdminNewRoute,
    pizzeriasPizzeriasAdminPizzasRoute: pizzeriasPizzeriasAdminPizzasRoute,
    pizzeriasPizzeriasAdminIndexRoute: pizzeriasPizzeriasAdminIndexRoute,
  }

const pizzeriasPizzeriasAdminRouteWithChildren =
  pizzeriasPizzeriasAdminRoute._addFileChildren(
    pizzeriasPizzeriasAdminRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  accountProfileRoute: accountProfileRoute,
  legalTermsAndConditionsRoute: legalTermsAndConditionsRoute,
  legalUnauthorizedRoute: legalUnauthorizedRoute,
  shopCartRoute: shopCartRoute,
  shopCheckoutRoute: shopCheckoutRouteWithChildren,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
  authAuthRegisterPizzeriaRoute: authAuthRegisterPizzeriaRoute,
  ordersOrdersIdRoute: ordersOrdersIdRoute,
  ordersOrdersAdminRoute: ordersOrdersAdminRoute,
  pizzeriasPizzeriasIdRoute: pizzeriasPizzeriasIdRoute,
  pizzeriasPizzeriasAdminRoute: pizzeriasPizzeriasAdminRouteWithChildren,
  ordersOrdersIndexRoute: ordersOrdersIndexRoute,
  pizzeriasPizzeriasIndexRoute: pizzeriasPizzeriasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@benjavicente/angular-start-experimental'
declare module '@benjavicente/angular-start-experimental' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
